context: principal

views:
  - name: nodes
    procedure: view-store
    privileges: none
  # - name: dashboard
  #   procedure: view-composite
  #   privileges: none

whitelist:
  - "127.0.0.1"

devDependencies:
  "mocha": "^7.1.0"
  "chai": "^4.2.0"

#don't change
procedure: view-gateway
