context: principle

views:
  - name: nodes
    procedure: view-store
    permissions: none
  - name: dashboard
    procedure: view-composite
    permissions: none

whitelist:
  - "127.0.0.1"

devDependencies:
  "mocha": "^7.1.0"
  "chai": "^4.2.0"

#don't change
procedure: view-gateway
