name: roles
domain: principal
service: base

contexts:
  - principal

devDependencies:
  "mocha": "^7.1.0"
  "chai": "^4.2.0"
  "sinon": "^7.3.2"
  "sinon-chai": "^3.3.0"

testing:
  dependencies:
    - domain: principal
      procedure: event-store
      service: base

  steps:
    - pre:
        - domain: principal
          service: base
          root: some-principal-root
          action: add-roles
          payload:
            roles:
              - id: some-role-id
                subject:
                  root: some-role-subject-root
                  service: some-role-subject-service
                  network: some.network
              - id: some-other-role-id
                subject:
                  root: some-other-role-subject-root
                  service: some-other-role-subject-service
                  network: some.other-network
      context:
        network: some.network
        principal:
          root: some-principal-root
      response:
        - id: some-role-id
          subject:
            root: some-role-subject-root
            service: some-role-subject-service
            network: some.network
    - pre:
        - domain: principal
          service: base
          root: some-other-principal-root
          action: add-scenes
          payload:
            scenes:
              - root: some-scene-root
                service: some-scene-service
                network: some.network
      context:
        network: some.network
        principal:
          root: some-other-principal-root
      response: []
    - context:
        network: some.network
        principal:
          root: some-missing-root
      code: 404

#don't change
procedure: fact
