name: roles
domain: principal
service: core

contexts:
  - principal

devDependencies:
  "mocha": "^7.1.0"
  "chai": "^4.2.0"
  "sinon": "^7.3.2"
  "sinon-chai": "^3.3.0"

testing:
  dependencies:
    - domain: principal
      procedure: event-store
      service: core

  steps:
    - pre:
        - domain: principal
          service: core
          root: some-principal-root
          action: add-roles
          payload:
            roles:
              - id: some-role-id
                root: some-role-root
                service: some-role-service
                network: some.network
              - id: some-other-role-id
                root: some-other-role-root
                service: some-other-role-service
                network: some.other-network
      context:
        network: some.network
        principal:
          root: some-principal-root
      response:
        - id: some-role-id
          root: some-role-root
          service: some-role-service
          network: some.network
    - pre:
        - domain: principal
          service: core
          root: some-other-principal-root
          action: add-scenes
          payload:
            scenes:
              - root: some-scene-root
                service: some-scene-service
                network: some.network
      context:
        network: some.network
        principal:
          root: some-other-principal-root
      response: []
    - context:
        network: some.network
        principal:
          root: some-missing-root
      code: 404

#don't change
procedure: fact
